### ISSUE TITLE
IconButton generates size prop as text, which crashes app

### ISSUE THREAD

**Issue by paulobear** [draftbit/react-native-jigsaw#224]
- Started using new IconButton, system keeps crashing 
  - Error in low level android libs: Error while updating property 'fontSize' in shadow node of type: RCTText
- I just updated my 4Bablio project (log out/in/code gen). Issue still exists.
- Just one of many screens this is defective in:
  - https://build.draftbit.com/apps/e4GZEGvd/screens/2oRbFf1o?c=C0TIY6w3&p=Configs

Generated code:
``` javascript
<View style={styles.ViewXW}>
    <IconButton <<<size="32">>> icon="Entypo/add-to-list" />
</View>
```

Should be:
``` javascript
<View style={styles.ViewXW}>
    <IconButton ***size={32}*** icon="Entypo/add-to-list" />
</View>
```

**Comment by peterpme** [comment]
Hey @paulobear sorry for the delay I've been out of town. This will be fixed shortly. Thank you for bringing this up!

**Comment by peterpme** [comment]
Hey @paulobear this should now be fixed. I went through your screen and updated the places where `size` was set to a string. I'm currently taking a look at the rest of the app and will see if there are any other places this needs to be fixed.

Thanks for reporting the issue and sorry for the experience!

**Comment by paulobear** [comment]
Are you saying that I had set it to a string in my design? That really
confuses me. I didn't think that I had. Once I found this issue I scrubbed
the design looking for this issue.

Paul E Ourada
BluSkai Systems
***@***.***
303-396-2872

**Comment by peterpme** [comment]
Hey @paulobear,

Sorry if I wasn't clear. It was definitely a bug on our end. The bug should be fixed now!

I also went through the database and scrubbed any incorrect values. The change might not be immediately reflected because the screen code is cached until you make _any_ change, but it shouldn't happen moving forward.

I hope that makes more sense!

**Comment by paulobear** [comment]
No worries, thanks for the update!
