### ISSUE TITLE
Upgrade & Fix Slider that works on iOS, Web and Android to replace react-native-slider

### ISSUE THREAD

**Issue by peterpme** [draftbit/react-native-jigsaw#48]
Slider component 

- [ ] make sure example slides and works appropriately on web, ios, android (i think its broken on web right now)
- [ ] make sure the slider has a value that can be passed in from props
- [ ] make sure it passes typescript types
- [ ] make sure theme variables can be consumed (this is not the case right now, they're just hex values):, colors are consumed as `theme.colors.primary`
- [ ] set the correct default props (as below) for both the component and SEED_PROPS and defaultValue

from the example app:
```
        <Slider
          style={{ height: 4 }}
          maximumTrackTintColor="#5a45ff" /* this should be "primary" */
          minimumTrackTintColor="#536070" /* this should be "light" */
          thumbTintColor="#5a45ff" /* this should be "primary" */
          thumbBorderRadius={4}
          trackBorderRadius={4}
          thumbSize={8}
          thumbTouchSize={4}
          value={value}
          minimumValue={0}
          maximumValue={10}
          step={1}
          onValueChange={handleChange}
        />
```

This is the current slider on web:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/1211905/91991809-feda8600-ecf8-11ea-8cc6-bc73ae670d3a.png">

we should update the colors to be a little more sensible (this slider looks weird!) see the code snippet above for the correct colors

the SEED_DATA values should also be mapped accordingly, for example:

```
    maximumTrackTintColor: {
      group: GROUPS.basic,
      label: "Maximum Color",
      description: "Color of the track from the right of the thumb",
      editable: true,
      required: false,
      formType: FORM_TYPES.color,
      propType: FORM_TYPES.THEME, /* any place that has formType of color also needs propType of THEME */
      defaultValue: null, /* should be "primary" */
    },
```

**Comment by YoussefHenna** [comment]
>  make sure theme variables can be consumed (this is not the case right now, they're just hex values):, colors are consumed as theme.colors.primary

Can you elaborate on that, don't really understand what is required.

**Comment by peterpme** [comment]
See how the values [here](https://github.com/draftbit/react-native-jigsaw/blob/master/example/src/SliderExample.js#L14) are hex values? What they should be instead is theme values:

before:
```
maximumTrackTintColor="#5a45ff"
minimumTrackTintColor="#536070"
thumbTintColor="#5a45ff"
```

after:
```
maximumTrackTintColor="primary"
minimumTrackTintColor="light"
thumbTintColor="primary"
```

and then in the code (Slider.tsx):

before:
```
minimumTrackTintColor={minimumTrackTintColor}
maximumTrackTintColor={maximumTrackTintColor}
```

after:
```
minimumTrackTintColor={theme.colors[minimumTrackTintColor]}
maximumTrackTintColor={theme.colors[maximumTrackTintColor]}
```

does that make sense?
