### ISSUE TITLE
Fix Carousel on Web to match Native experience

### ISSUE THREAD

**Issue by peterpme** [draftbit/react-native-jigsaw#54]
The Carousel component on web doesn't swipe and the image ratio is off

- [ ] image ratios seem to be broken. it's a square on ios (and presumably android) but a long rectangle on web. the ratio should work the same way on web as it does local
- [ ] swiping doesn't work on web

carousel on web:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1211905/92272264-da280f00-eeae-11ea-8cf6-2eb096c0878c.png">

carousel on ios: 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/1211905/92272229-c5e41200-eeae-11ea-9ed5-fe29539bd580.png">

### possible solutions
- react-native-gesture-handler: check out the [SwipeableTable example located here](https://snack.expo.io/@adamgrzybowski/react-native-gesture-handler-demo):

The file on expo is: 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/1211905/92272767-cf21ae80-eeaf-11ea-94c6-44fda92867fe.png">

here's how to get to the example on your phone (after scanning QR code):
<img width="304" alt="image" src="https://user-images.githubusercontent.com/1211905/92272632-8538c880-eeaf-11ea-976b-b0e0ff6aa2ed.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/1211905/92272574-689c9080-eeaf-11ea-8d84-639bf4fe00ff.png">

swiping works correctly and we would just need to copy over their Swipeable and pass in the right props to the carousel component

- fix the ScrollView swiping. This one feels a little trickier. Since it's implemented already, maybe there's a hack somewhere or we're missing somethign?

**Comment by YoussefHenna** [comment]
I can't see how we can use the Swipeable component to fix the carousel. Check [https://docs.swmansion.com/react-native-gesture-handler/docs/component-swipeable/](this), swipeable is only used to add action buttons to swipeable components, how would we use this to replace swiping of scroll view.

**Comment by YoussefHenna** [comment]
As for the aspect ratio issue, it was caused because default height was hard-coded to 250, which looked weird when put on a very wide screen (web browser). I changed it to a value more dependent on the screen size.

**Comment by peterpme** [comment]
@YoussefHenna thanks for letting me know!

height: that makes sense, but lets keep it 250 cause we only support mobile web right now (so maybe it should be wrapped in an aspect ratio instead?), otherwise lets make it 275 and see what it looks like 

component-swipeable: ohh i see what you mean, woops! i think the way you did it is great, thanks!!
