### ISSUE TITLE
Crash: "Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider".

### ISSUE THREAD

**Issue by StartupSam** [draftbit/react-native-jigsaw#92]
I only run into this problem when I attempt to upgrade my @draftbit/ui version past 37.3.0. Already tried restarting Expo bundler, app, etc. Also tried all the solutions present in this GitHub thread: https://github.com/th3rdwave/react-native-safe-area-context/issues/110.

I'm not sure exactly where the issues start but I'm pretty sure it's present at the first version 38. The only fix I've found is to downgrade the Draftbit UI package.

Any ideas what might be causing this issue, or how I might track down what's causing the conflict?

**Comment by StartupSam** [comment]
Quick update: Seems like the copy of react-native-safe-area-view in Draftbit was conflicting with the Expo copy. My temporary super hacky solution is to add "postinstall": "rm -rf node_modules/expo/node_modules/react-native-safe-area-context && rm -rf node_modules/@draftbit/ui/node_modules/react-native-safe-area-context" to my scripts in package.json.

**Comment by StartupSam** [comment]
@peterpme Is this fixed in an update?

**Comment by peterpme** [comment]
Hey @StartupSam yes it shouldn't be happening anymore. Thanks for checking in!
